### ISSUE TITLE
Incorrect Namespacing

### ISSUE THREAD

**Issue by MichaelMacDonald54** [RusticiSoftware/scormcloud-api-v2-client-php#1]
All the classes within directories seem to have their namespaces doubled.

the src/Api/ApplicationManagementApi.php class for example has it's namespace set to:

```namespace RusticiSoftware\Cloud\V2\RusticiSoftware\Cloud\V2\Api;```

If I change it to just ```namespace RusticiSoftware\Cloud\V2\Api;``` 

Then it loads properly when attempting to "use" it.

This is consistent in all files within the Api directory and the Model directory.

**Comment by DillGromble** [comment]
Closing as resolved by #2
