### ISSUE TITLE
Deprecation warning: require.RusticiSoftware/scormcloud-api-v2-client-php is invalid

### ISSUE THREAD

**Issue by zanderwar** [RusticiSoftware/scormcloud-api-v2-client-php#10]
> It should not contain uppercase characters. Please use rusticisoftware/scormcloud-api-v2-client-php instead. Make sure you fix this as Composer 2.0 will error.

**Comment by jtennies10** [comment]
This looks to have subsided as a result of the new installation method we recommend. However, this is something we are monitoring and will address if need be. Thanks for bringing it to our attention!
