### ISSUE TITLE
Cannot update the new version of the package

### ISSUE THREAD

**Issue by monikamich** [RusticiSoftware/scormcloud-api-v2-client-php#19]
Method  CourseApi::createUploadAndImportCourseJobWithHttpInfo() accepts bool param $may_create_new_version but ApiClient::callApi() method converts 'true' bool value to int '1'.  API method only accepts boolean values. It does not recognizes mayCreateNewVersion passed as int.

Here is an example of the request:

[DEBUG] HTTP Request body  ~BEGIN~
Array
(
    [file] => CURLFile Object
        (
            [name] => /tmp/phpxNLAFV
            [mime] => 
            [postname] => 
        )

)

~END~
*   Trying 54.230.31.111:443...
* TCP_NODELAY set
* Connected to cloud.scorm.com (54.230.31.111) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=cloud.scorm.com
*  start date: Jan  8 00:00:00 2021 GMT
*  expire date: Feb  5 23:59:59 2022 GMT
*  subjectAltName: host "cloud.scorm.com" matched cert's "cloud.scorm.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55e2ab9d9150)
> POST /api/v2//courses/importJobs/upload?courseId=any_course_id&mayCreateNewVersion=1 HTTP/2
Host: cloud.scorm.com
user-agent: Swagger-Codegen/1.0.0/php
accept: application/json
authorization: Basic basic_token_auth
content-length: 411332
content-type: multipart/form-data; boundary=------------------------6fcc904db869c4fd

* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* We are completely uploaded and fine
< HTTP/2 409 
< content-type: application/json
< content-length: 115
< date: Mon, 18 Oct 2021 20:47:25 GMT
< server: Apache
< cache-control: no-cache, no-store
< pragma: no-cache
< expires: -1
< access-control-allow-origin: *
< access-control-allow-credentials: true
< access-control-allow-headers: origin, content-type, accept, authorization, uploadedContentType
< access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
< x-xss-protection: 1; mode=block
< x-cache: Error from cloudfront
< via: 1.1 4d912df0fbfee070703a7e2b8fa4ff68.cloudfront.net (CloudFront)
< x-amz-cf-pop: ATL56-C3
< x-amz-cf-id: Lsfsdfwv 23g==
< 
* Connection #0 to host cloud.scorm.com left intact
[DEBUG] HTTP Response body ~BEGIN~
{"error":"Course [any_course_id] already exists in app [app_id] and new version creation was not requested."}
~END~

**Comment by mjschuetze102** [comment]
We have fixed the issue with passing boolean values as strings in #21. As noted previously, both string and boolean values will work moving forward in order to preserve backwards compatibility. I'm going to go ahead and close the ticket. Let us know if you run into any more problems working with the new version.
