### ISSUE TITLE
Getting authorization required error

### ISSUE THREAD

**Issue by colonize8** [RusticiSoftware/scormcloud-api-v2-client-php#22]
I have used the sample code as it is with my app_id and secret and I get this error in the browser:

[401] Client error: `POST https://cloud.scorm.com/api/v2//appManagement/token` resulted in a `401 401` response: {"error":"Authorization Required."}

Using the same details in the web site the authorization works and the curl commands connect correctly too with those details encoded:
https://cloud.scorm.com/docs/v2/reference/swagger/

Am I missing anything?

**Comment by mjschuetze102** [comment]
My best guess would be that the following line was commented out:

```php
// Set the default configuration values for new configuration objects
ScormCloud\Configuration::setDefaultConfiguration($config);
```

Send an email to support@rusticisoftware.com and we'll happily work with you to solve this problem.

**Comment by colonize8** [comment]
Thanks to support we were able to solve the problem.

I had an old version of composer that was not installing the latest version of the library.
