### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by monikamich** [RusticiSoftware/scormcloud-api-v2-client-php#23]
The library cannot be pulled while using PHP 8.

**Comment by mjschuetze102** [comment]
Hello. Could you be more specific? I am able to run the library with PHP 8.0.12. Is there some sort of error message that you are seeing that would help in diagnosing the problem?

**Comment by monikamich** [comment]
Hi. I was running composer 2.3.9 and I was able to pull the library with php 7.4 but not with 8.0 neither 8.1. I update composer to 2.4.0 and it works now.

Thank you.
