### ISSUE TITLE
Boolean query parameters converting to integer value, API not returning desired response

### ISSUE THREAD

**Issue by dkjensen** [RusticiSoftware/scormcloud-api-v2-client-php#8]
The SCORM Cloud API seems to not accept integer values where it expects a true/false value.

Take the /courses endpoint for example. Requesting a list of all courses using the getCourses method, there are 2 parameters `include_registration_count` and `include_course_metadata` that have the parameter values set as boolean. 

If I call the method
```
/**
 * 7th parameter is include registration count
 */
$course->getCourses( null, null, null, null, null, null, true, false );
```

I expect the registration count to be present in the response, however it is not. This is because when the query URL is built, it is using the PHP `http_build_query` function which converts boolean values to integer, thus making the request:

https://cloud.scorm.com/api/v2/courses?includeRegistrationCount=1

This will not return the registration count in the response.

Instead you must use the value `true` as a string:
`$course->getCourses( null, null, null, null, null, null, 'true', false );`

Which will then generate the request URL:

https://cloud.scorm.com/api/v2/courses?includeRegistrationCount=true

This has not been tested on other methods but one could assume this to be true across the board. This could be fixed by converting the boolean values to string before passing into `http_build_query`, however like I said this has not been tested on any other methods so I am not aware of any implications.

**Comment by jtennies10** [comment]
Hi David, the team has discussed this over the past few months, and we've decided to leave the behavior as is. We believe this a pretty easy accommodation to make, whereas it would add complexity to the code generation process to fix properly. We've added a note in the README to let new users know of this behavior. Thanks for your understanding and report!
